language: go
go:
  - 1.7
before_install:
  - go get -t -v ./...
  - go get github.com/golang/lint/golint
install:
before_script:
  - go vet ./...
  - golint ./... | xargs --no-run-if-empty false
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
